name: Hello world workflow

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Say hello
      run: echo "Hello, GitHub Actions!"